version: '3.9'

services:
  weather-db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
